[package]
name = "sealion_uci_uif"
edition.workspace = true
version.workspace = true
publish.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
nom = "7"
thiserror = "1"
